### ISSUE TITLE
How can I edit the style for "No Highlighting"?

### ISSUE THREAD

**Issue by chris-relaxing** [AndiDittrich/WordPress.Enlighter#71]
I just started using Enlighter and am investigating creating my own highlighting styles. However, I couldn't find a css file for "No Highlighting" but would like to create my own version of this style. How can I do it?

**Comment by AndiDittrich** [comment]
Hi chris,

the token styles as well as the "no highlighting" styling are located in the EnlighterJS CSS file delivered with the plugin. to override these style, take a look into a [theme or your choice](https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Themes/Enlighter.css#L127), especially the `.<themename>EnlighterJSWrapper pre` selector. in this case the code is simply wrapped in a `pre` tag

**Example**

```css
/* Raw Code Pane */
.enlighterEnlighterJSWrapper pre{
	background-color: #ffffff;
	font-size: 12px;
	color: #717171;
}
```

br, Andi
